name: Check Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: debian-latest
    strategy:
      matrix:
        node-version: [20.x]
        bun-version: [1.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install
        env:
          HUSKY: 0

      - name: Run build
        run: bun run build
        env:
          NODE_ENV: production
